//
// Created by naomi on 25/05/2024.
//

#ifndef INC_20465_SYSTEM_PROGRAMMING_LABORATORY_FINAL_PROJECT_GENERAL_H
#define INC_20465_SYSTEM_PROGRAMMING_LABORATORY_FINAL_PROJECT_GENERAL_H

#define MAX_LINE_LENGTH 81
#define MAX_LABLE_LENGTH 30

/* Define a Boolean Type */
typedef enum { false, true } bool;

#endif //INC_20465_SYSTEM_PROGRAMMING_LABORATORY_FINAL_PROJECT_GENERAL_H
